apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-route
  namespace: frontend
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`area.oden-app.com`) || PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend-service
          port: 80