apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_API_URL: "http://34.140.49.18"
  VITE_GOOGLE_CLIENT_ID: "825177499555-t5r2vd2u6sud877v1a63kmus89j8vh41.apps.googleusercontent.com"
  VITE_ATLASSIAN_CLIENT_ID: "m930BhmUp6A8VER2jBE1KI3Fa9ru9E6Q"
  VITE_GITHUB_CLIENT_ID: "Ov23liBNjNSBdooODldz"
  VITE_SPOTIFY_CLIENT_ID: "c492c8e69e99485bb8b0be0f558e3648"
  VITE_DISCORD_CLIENT_ID: "1298669583082852382"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: area-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: area-frontend
  template:
    metadata:
      labels:
        app: area-frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/area-cluster/area-frontend:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /
              port: 8081
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: area-frontend
spec:
  selector:
    app: area-frontend
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer