services:
  # database:

  queue:
    build:
      context: ./apps/queue
    image: queue
    container_name: queue
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./apps/queue/.env



  # manager:
  # worker:
  # server:
  # client_mobile:
  # client_web:

