services:
  queue:
    build:
      context: ./apps/queue
    image: queue
    container_name: queue
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./apps/queue/.env
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - area-network

  manager:
    build:
      dockerfile: ./apps/task_manager/Dockerfile
    image: manager
    container_name: manager
    env_file:
      - ./apps/task_manager/.env
    depends_on:
      queue:
        condition: service_healthy
    restart: always
    networks:
      - area-network

  worker:
    build:
      dockerfile: ./apps/worker/Dockerfile
    image: worker
    container_name: worker
    env_file:
      - ./apps/worker/.env
    depends_on:
      queue:
        condition: service_healthy
    networks:
      - area-network

  server:
    build:
      dockerfile: ./apps/api/Dockerfile
    image: server
    container_name: server
    env_file:
      - ./apps/api/.env
    depends_on:
      queue:
        condition: service_healthy
      manager:
        condition: service_started
      worker:
        condition: service_started
    networks:
      - area-network
    ports:
      - "8080:8080"

  client_mobile:
    build:
      dockerfile: ./apps/mobileExpo/Dockerfile
      args:
        SKIP_MOBILE_COMPILATION: ${SKIP_MOBILE_COMPILATION:-0}
    image: mobile-expo
    container_name: mobile-expo
    env_file:
      - ./apps/mobileExpo/.env
    volumes:
      - apk-volume:/shared
    networks:
      - area-network

  client_web:
    build:
      dockerfile: ./apps/frontend/Dockerfile
    image: frontend
    container_name: frontend
    env_file:
      - ./apps/frontend/.env
    depends_on:
      client_mobile:
        condition: service_completed_successfully
      server:
        condition: service_started
    volumes:
      - apk-volume:/shared
    networks:
      - area-network
    expose:
      - 8081
    ports:
      - "8081:8081"

networks:
  area-network:
    driver: bridge

volumes:
  apk-volume: