services:
  # database:

  queue:
    build:
      context: ./apps/queue
    image: queue
    container_name: queue
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./apps/queue/.env
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  manager:
    build:
      dockerfile: ./apps/task_manager/Dockerfile
    image: manager
    container_name: manager
    env_file:
      - ./apps/task_manager/.env
    depends_on:
      queue:
        condition: service_healthy
    restart: always
    network_mode: "host"

  worker:
    build:
      dockerfile: ./apps/worker/Dockerfile
    image: worker
    container_name: worker
    env_file:
      - ./apps/worker/.env
    depends_on:
      queue:
        condition: service_healthy
    network_mode: "host"

  server:
    build:
      dockerfile: ./apps/api/Dockerfile
    image: server
    container_name: server
    env_file:
      - ./apps/api/.env
    depends_on:
      queue:
        condition: service_healthy
      manager:
        condition: service_started
      worker:
        condition: service_started
    network_mode: "host"
    ports:
      - "8080:8080"

  client_mobile:
    build:
      dockerfile: ./apps/mobileExpo/Dockerfile
    image: mobile-expo
    container_name: mobile-expo
    env_file:
      - ./apps/mobileExpo/.env
    volumes:
      - apk-volume:/shared
    network_mode: "host"

  client_web:
    build:
      dockerfile: ./apps/frontend/Dockerfile
    image: frontend
    container_name: frontend
    env_file:
      - ./apps/frontend/.env
    depends_on:
      client_mobile:
        condition: service_completed_successfully
      server:
        condition: service_started
    volumes:
      - apk-volume:/shared
    network_mode: "bridge"
    expose:
      - 8081
    ports:
      - "8081:8081"

volumes:
  apk-volume:
