export enum ReactionTypes {
  EXAMPLE_REACTION = "EXAMPLE_REACTION",
  SEND_EMAIL = "SEND_EMAIL",
  CREATE_GOOGLE_TASK = "CREATE_GOOGLE_TASK",
  SEND_MESSAGE_TO_DISCORD_WEBHOOK = "SEND_MESSAGE_TO_DISCORD_WEBHOOK",
  CREATE_PULL_REQUEST_COMMENT = "CREATE_PULL_REQUEST_COMMENT",
  SEND_SCROBBLE_REPORT_BY_MAIL = "SEND_SCROBBLE_REPORT_BY_MAIL",
  SEND_ALBUMS_REPORT_BY_MAIL = "SEND_ALBUMS_REPORT_BY_MAIL",
  SEND_ARTISTS_REPORT_BY_MAIL = "SEND_ARTISTS_REPORT_BY_MAIL",
  CREATE_JIRA_TICKET = "CREATE_JIRA_TICKET",
}
