export enum ReactionTypes {
  EXAMPLE_REACTION = "EXAMPLE_REACTION",
  SEND_EMAIL = "SEND_EMAIL",
  CREATE_GOOGLE_TASK = "CREATE_GOOGLE_TASK",
  SEND_MESSAGE_TO_DISCORD_WEBHOOK = "SEND_MESSAGE_TO_DISCORD_WEBHOOK",
  COMMENT_GITHUB_ISSUE = "COMMENT_GITHUB_ISSUE",
  SEND_SCROBBLE_REPORT_BY_MAIL = "SEND_SCROBBLE_REPORT_BY_MAIL",
  SEND_ALBUMS_REPORT_BY_MAIL = "SEND_ALBUMS_REPORT_BY_MAIL",
  SEND_ARTISTS_REPORT_BY_MAIL = "SEND_ARTISTS_REPORT_BY_MAIL",
  COMMENT_YOUTUBE_VIDEO = "COMMENT_YOUTUBE_VIDEO",
  CREATE_JIRA_TICKET = "CREATE_JIRA_TICKET",
}
