export enum ReactionTypes {
    EXAMPLE_REACTION = 'EXAMPLE_REACTION',
    SEND_EMAIL = 'SEND_EMAIL',
    CREATE_GOOGLE_TASK = 'CREATE_GOOGLE_TASK',
    SEND_MESSAGE_TO_DISCORD_WEBHOOK = 'SEND_MESSAGE_TO_DISCORD_WEBHOOK'
}
