export enum ActionTypes {
  EXAMPLE_ACTION = "EXAMPLE_ACTION",
  EACH_X_SECONDS = "EACH_X_SECONDS",
  ON_YOUTUBE_VIDEO_POSTED = "ON_YOUTUBE_VIDEO_POSTED",
  ON_NEW_JIRA_TICKET = "ON_NEW_JIRA_TICKET",
  ON_NEW_JIRA_PROJECT = "ON_NEW_JIRA_PROJECT",
  ON_NEW_GITHUB_REPOSITORY = "ON_NEW_GITHUB_REPOSITORY",
  ON_PULL_REQUEST_STATE = "ON_PULL_REQUEST_STATE",
  ON_NEW_VIDEO_IN_PLAYLIST = "ON_NEW_VIDEO_IN_PLAYLIST",
  ON_SPOTIFY_PLAYLIST_UPDATE = "ON_SPOTIFY_PLAYLIST_UPDATE",
  ON_NEW_ARTIST_CONTENT = "ON_NEW_ARTIST_CONTENT",
  ON_NEW_GOOGLE_TASK = "ON_NEW_GOOGLE_TASK",
}
