export enum ActionTypes {
    EXAMPLE_ACTION = 'EXAMPLE_ACTION',
    EACH_X_SECONDS = 'EACH_X_SECONDS',
    ON_YOUTUBE_VIDEO_POSTED = 'ON_YOUTUBE_VIDEO_POSTED',
    ON_NEW_JIRA_TICKET = 'ON_NEW_JIRA_TICKET',
    ON_NEW_JIRA_PROJECT = 'ON_NEW_JIRA_PROJECT',
}