apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs-container
          image: gcr.io/area-cluster/backend:${GITHUB_SHA}
          ports:
            - containerPort: 3001
          imagePullPolicy: Always