apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker-container
          image: gcr.io/$PROJECT_ID/worker:$GITHUB_SHA
          env:
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_PORT
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_PASSWORD
            - name: MONGODB_AUTH_SOURCE
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_AUTH_SOURCE
            - name: MONGODB_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_DB_NAME
            - name: MONGODB_TLS_CA_FILE
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_TLS_CA_FILE
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: RMQ_HOST
              value: "34.79.122.15"
            - name: RMQ_QUEUE
              value: "queue"
