export const mailStyle =
`<head>
    <style>
    body {
        font-family: Arial, sans-serif;
        line-height: 1.6;
        color: #333;
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
    }
    .highlight {
        font-weight: bold;
        color: #1db954;
    }
    .track-list {
        list-style-type: none;
        padding: 0;
    }
    .track-item {
        margin: 10px 0;
        padding: 10px;
        border-bottom: 1px solid #eee;
    }
    .playcount {
        color: #666;
        font-size: 0.9em;
    }
    .note {
        color: #666;
        font-style: italic;
        margin: 10px 0;
    }
    </style>
</head>`;

export const mailFooter = 
`
<p style="margin-top: 20px; color: #666; font-size: 0.8em;">
    Generated by your weekly music tracking system
</p>
`

