name: Prettify Code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run_prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Hide package.json
        run: mv package.json package.json.bkp

      - name: Download Svelte Prettier Plugin
        run: npm i --no-save prettier-plugin-svelte

      - name: Un-hide package.json
        run: mv package.json.bkp package.json

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          same_commit: true
          prettier_plugins: prettier-plugin-svelte
