name: Prettify Code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run_prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Disable lock creation
        run: npm config set package-lock false

      - name: Download Svelte Prettier Plugin
        run: npm i

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          prettier_plugins: prettier-plugin-svelte
          only_changed: True
